### ISSUE TITLE
Request- Generate prospective rating plan

### ISSUE THREAD

**Issue by isbell** [gtlaflair/rrasch#1]
Instead of relying on the sample dataset to draw samples for a rating plan, it would be helpful to be able to generate a prospective rating plan based on known numbers of responses, observations per response, and raters.

Something like:
ID = integer for number of unique responses to be scored
O = integer for number of observations per response
R = number of raters

Based on these parameters, assign Rater1-RaterO for each ID in a fashion that will be fully linked in FACETS.

**Comment by gtlaflair** [comment]
rate_plan does not rely on data from previously administered tests anymore. It requires the user to know/guess at the number of responses, number of tasks, and number of raters. From this information, it will generate a file for testing in Facets in order to evaluate the link among the data
